version: '2'

### Notes
## configuration
#
## containers
#
# mariadb
# - a mysql compatible database for storing data in a relational database
#
# phpmyadmin
# - administration panel for mysql, an ease of use tool
#
## docker-compose commands 
#
# starting containers
# - run ```docker-compose up```
#
# starting containers with full rebuild
# - run ```docker-compose up --build --force-recreate```
#
# run container as daemon
# - run ```docker-compose up -d```
#
# stopping daemonized containers
# - run ```docker-compose down```
#

services:
  # Mariadb database for NodeJS applications
  db:
    build: ./database
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  # Do not expose to internet
  # - database takes awhile to start up,
  # phpMyAdmin will show errors if trying to
  # connect to early
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 8081:80
    depends_on:
      - db
